apiVersion: v1
kind: Namespace
metadata:
  name: locol

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: locol-player-core-config-json
  namespace: locol
data:
  system.json: |
    {
        "socketioServer": "http://uat-api.locol.media:8151",
        "apiServer": "http://uat-api.locol.media:8080",
        "player": "http://locol-player-core" 
          
    }

---

apiVersion: v1
kind: Service
metadata:
  name: service-locol-player-core
  namespace: locol
spec:
  ports:
  - name: api-port
    port: 7080
    protocol: TCP
    targetPort: 7080
    nodePort: 30080
  - name: ws-port
    port: 7081
    protocol: TCP
    targetPort: 7081
    nodePort: 30081
  selector:
    app: locol-player-core
  sessionAffinity: None
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: locol-player-core-deployment
  namespace: locol
  labels:
    app: locol-player-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locol-player-core
  template:
    metadata:
      labels:
        app: locol-player-core
    spec:
      containers:
      - name: locol-player-core
        image: locolmedia/player-core
        imagePullPolicy: Always
        volumeMounts:
          - name: config-volume 
            mountPath: /locol/configMaps
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "200m"            
        ports:
          - containerPort: 7080
          - containerPort: 7081
      volumes:
        - name: config-volume
          configMap:
            name: locol-player-core-config-json
